# Generated by Django 3.2.2 on 2021-05-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
