# Generated by Django 3.2.2 on 2021-06-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20210605_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='modelvariant',
        ),
        migrations.DeleteModel(
            name='ModelVariant',
        ),
    ]
