# Generated by Django 3.2.2 on 2021-05-22 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210521_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aboutpage',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
